export const SET_USER = 'SET_USER';
export const SET_USER_LISTS = 'SET_USER_LISTS';
export const SET_USER_LISTS_DIALOG = 'SET_USER_LISTS_DIALOG';
export const SET_USER_LOGGING = 'SET_USER_LOGGING';
export const SET_SNACKBAR = 'SET_SNACKBAR';
export const SET_CREATE_LIST_DIALOG = 'SET_CREATE_LIST_DIALOG';
export const CREATE_LIST_DIALOG = 'CREATE_LIST_DIALOG';